/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
  */

    saurusSidebar: {
        "課題定義": [
            "sec_Plan_1015_2021_4066/c_Problem_1015_2021_b66d/c_Problem_1015_2021_b66d",
        ],
        "Docsaurusの初期設定": [
            "sec_Docsaurus_1012_2021_71a8/c_Setup_1012_2021_4d8d/c_Setup_1012_2021_4d8d",
            "sec_Docsaurus_1012_2021_71a8/c_DocOnly_1014_2021_46fb/c_DocOnly_1014_2021_46fb",
            "sec_Docsaurus_1012_2021_71a8/c_Config2_1014_2021_3e1d/c_Config2_1014_2021_3e1d",
            "sec_Docsaurus_1012_2021_71a8/c_Config_0904_2021_b7db/c_Config_0904_2021_b7db",
            "sec_Docsaurus_1012_2021_71a8/c_FullTextSearch_1015_2021_59bf/c_FullTextSearch_1015_2021_59bf",
            "sec_Docsaurus_1012_2021_71a8/c_i18n_1015_2021_2a40/c_i18n_1015_2021_2a40",
        ]
    }
};
